@author = "REPLACE_WITH_BLOG_AUTHOR"
@url = "REPLACE_WITH_BLOG_URL"
@title = "REPLACE_WITH_BLOG_TITLE"


POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": {{author}},
  "url": {{url}},
  "title": {{title}}
}
